#!/bin/bash

#Create symlinks for the configs
if [ ! -h ~/.ssh/config ]; then
    ln -s ~/bin/nix_conf/ssh/config ~/.ssh/config
fi;

if [ ! -h ~/.gitconfig ]; then
    ln -s ~/bin/nix_conf/git/gitconfig ~/.gitconfig
fi; 

if [ ! -h ~/.gitk ]; then
    ln -s ~/bin/nix_conf/git/gitk ~/.gitk
fi;

if [ ! -h ~/.vimrc ]; then
    ln -s ~/bin/nix_conf/vim/vimrc ~/.vimrc
fi;

if [ ! -h ~/.vim ]; then
    ln -s ~/bin/nix_conf/vim/vim ~/.vim
fi;

if [ ! -h ~/.tmux.conf ]; then
    ln -s ~/bin/nix_conf/tmux.conf ~/.tmux.conf
fi;

#create a .tmp directory for vim backups
if [ ! -d ~/.tmp ]; then
    mkdir ~/.tmp;
fi;

#checkout the pathogen submodules and whatnot
if [ ! "$(ls -A ~/bin/nix_conf/pathogen)" ]; then
    git submodule update --init
fi;
