#!/bin/bash

export DOTDOT="${HOME}/bin/nix_conf"

#Create symlinks for the configs
if [ ! -h ~/.bashrc ]; then
    if [ -f ~/.bashrc ]; then #there's a file there to remove
        mv ~/.bashrc ~/.bashrc.old
    fi;
    ln -s ${DOTDOT}/bashrc ~/.bashrc
    source ~/.bashrc
    if [ -f ~/.bash_profile ]; then
        mv ~/.bash_profile ~/.bash_profile.old
    fi;
    if [ ! -f ~/.bash_profile ]; then
        echo ". ~/.bashrc" >> ~/.bash_profile
    fi
fi;


# First level symlinks
for rc in inputrc fdignore ctags pythonstartup ackrc editorconfig ideavimrc pdbrc virtualenv aider.conf.yml; do
    if [ ! -h ~/.$rc ]; then
        ln -s ${DOTDOT}/"$rc" ~/."$rc"
    else
        echo "File ~/.$rc already exists"
    fi
done


# Deeper symlinks
for rc in git/gitconfig git/gitk vim/vimrc vim/vim tmux/tmux.conf mutt/muttrc; do
    RCFILE=$(basename "./$rc")
    if [ ! -h ~/."$RCFILE" ]; then
        ln -s ${DOTDOT}/"$rc" ~/."$RCFILE"
    else
        echo "File ~/.$RCFILE already exists"
    fi;
done


if [ ! -h ~/.ssh/config ]; then
    ln -s ${DOTDOT}/ssh/config ~/.ssh/config
fi;

if [ ! -h ~/.pip ]; then
    mkdir ~/.pip;
    ln -s ${DOTDOT}/pip.conf ~/.pip/pip.conf
fi;

if [ ! -f ~/.prettierrc.json ]; then
    ln -s ${DOTDOT}/.prettierrc.json ~/.prettierrc.json
fi;

# Ensure the destination directory exists
mkdir -p ~/Library/Application\ Support/espanso

# Link the config and match directories
ln -s ~/bin/nix_conf/espanso/config ~/Library/Application\ Support/espanso/config
ln -s ~/bin/nix_conf/espanso/match ~/Library/Application\ Support/espanso/match

#create a .tmp directory for vim backups
if [ ! -d ~/.tmp ]; then
    mkdir ~/.tmp;
fi;

git submodule update --init;
