#!/bin/bash
# This hook is run after a new virtualenv is activated.
# borrowed from https://gist.github.com/acdha/4034103, tho turned off quiet pip install

set -e

(cat <<'PYDOC'
#!/usr/bin/env python
import pydoc
if __name__ == '__main__':
    pydoc.cli()
PYDOC
) > $VIRTUAL_ENV/bin/pydoc
chmod +x $VIRTUAL_ENV/bin/pydoc

pip install -q pep8 flake8 pyflakes ipython ipdb 
