matches:
  # Dates
  - trigger: ":today"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Web
  - trigger: ":gh"
    replace: "https://github.com/edwelker/"
  - trigger: ":li"
    replace: "https://www.linkedin.com/in/edwardwelker/"
  - trigger: ":ew"
    replace: "https://eddiewelker.com"
  - trigger: ":cal"
    replace: "https://calendar.google.com/calendar/"
  - triggers: [":ghs", ":ghsearch"]
    replace: "https://github.com/search?q=$|$"

  # Development
  - trigger: ":py"
    replace: "#!/usr/bin/env python3\n\ndef main():\n    pass\n\nif __name__ == \"__main__\":\n    main()"
  - trigger: ":iso"
    replace: "{{isodate}}"
    vars:
      - name: isodate
        type: date
        params:
          format: "%Y-%m-%dT%H:%M:%S%z"

  # Networking
  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl -s https://ifconfig.me"
